services:
  postgres-api:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
      TZ: Asia/Bangkok
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-sonarqube:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
      TZ: Asia/Bangkok
    volumes:
      - postgres_sonarqube_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sonarqube-network

  sonarqube:
    image: sonarqube:community
    restart: unless-stopped
    depends_on:
      postgres-sonarqube:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-sonarqube:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    networks:
      - sonarqube-network

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a strong-password ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["redis-server", "--requirepass", "strong-password"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  postgres_sonarqube_data:
  sonarqube_data:
  redis_data:

networks:
  sonarqube-network:
    driver: bridge
